<h1>Komentarze</h1>

<table class="table">
    <thead>
    <tr>
        <th>Data dodania</th>
        <th>Nazwa użytkownika</th>
        <th>Treść komentarza</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->comments as $mm): ?>
        
        <tr>
            <td><?= $mm->snippet->topLevelComment->snippet->publishedAt?></td>
            <td><?= $mm->snippet->topLevelComment->snippet->authorDisplayName?></td>
            <td><?= $mm->snippet->topLevelComment->snippet->textDisplay?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>