<h1>Lista punktów</h1>

<table class="table">
    <thead>
    <tr>
        <th>Lat</th>
        <th>Lang</th>
        <th>Address</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->mapmarkers as $mm): ?>
        <tr>
            <td><?= $mm->Lat ?></td>
            <td><?= $mm->Lang ?></td>
            <td><?= $mm->Address ?></td>
            <td><?= $mm->Description ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>