<html>
<style>
img {max-height:125px; margin:3px; border:1px solid #dedede;}
</style>
<body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script>

$(document).ready(function(){
  $("button").click(function(){
    var search=$("#search").val()
    console.log(search)
    var request = {
    "async": true,
    "crossDomain": true,
    "url": "https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=9b04ce39309e4ec4a4c82aa49b65bf6c&text="+search+"&format=json&nojsoncallback=1",
    "method": "GET",
    "headers": {}
    }

$.ajax(request).done(function (data) {
  console.log(data);



$("#galleryTitle").append(data.photos.photo[0].title + " Gallery");
    	$.each( data.photos.photo, function( i, gp ) {

var farmId = gp.farm;
var serverId = gp.server;
var id = gp.id;
var secret = gp.secret;

console.log(farmId + ", " + serverId + ", " + id + ", " + secret);

//  https://farm{farm-id}.staticflickr.com/{server-id}/{id}_{secret}.jpg

$("#flickr").append('<img src="https://farm' + farmId + '.staticflickr.com/' + serverId + '/' + id + '_' + secret + '.jpg"  onclick="window.open(this.src)"/>');

});
});
});
});
</script>


<h2><div id="galleryTitle"></div></h2>
<div style="clear:both;"/>
<div id="flickr"/>
    <div class="form-group">
        <input type="text" name="phrase" class="form-control" placeholder="Fraza" id="search"/>
    </div>
    <button class="btn btn-primary">Get Flickr photos</button>
</body>
</html>
