<h1><?= $tytul ?></h1>
<div class="row">
    <div class="col-lg-4">
        <?= $this->form()->openTag($form) ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('FileName')) ?>
            <?= $this->formText($form->get('FileName')) ?>
            <?= $this->formElementErrors($form->get('FileName'), ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('FileContent')) ?>
            <?= $this->formText($form->get('FileContent')) ?>
            <?= $this->formElementErrors($form->get('FileContent'), ['class' => 'help-block']) ?>
        </div>
        <?= $this->formSubmit($form->get('zapisz')) ?>

        <?= $this->form()->closeTag($form) ?>
    </div>
</div>