<h1>Lista plików</h1>

<?php if (!empty($this->msg)): ?>
    <div class="alert alert-danger">
        <?= $this->msg ?>
    </div>
<?php else: ?>
    <?php if (empty($this->files)): ?>
        <p>Brak plików.</p>
    <?php else: ?>
        <table style="width:100%">
        <tr>
			<th>Nazwa</th>
			<th>Operacje</th>
		</tr>
            <?php foreach ($this->files as $file): ?>
                <tr>
                    <td>
                        <a href="<?= $this->url('dropbox/default', ['action' => 'download'], ['query' => ['path' => $file['path_lower']]]) ?>">
                            <?= $file['name'] ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?= $this->url('dropbox/default', ['action' => 'edytuj'], ['query' => ['path' => $file['path_lower']]]) ?>" title="edytuj rekord">Edytuj</a>
                        <a href="<?= $this->url('dropbox/default', ['action' => 'usun'], ['query' => ['path' => $file['path_lower']]]) ?>" title="usuń rekord">Usuń</i></a>
                        <a href="<?= $this->url('dropbox/default', ['action' => 'download'], ['query' => ['path' => $file['path_lower']]]) ?>" title="ściągnij">Ściągnij</i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <a href="<?= $this->url('dropbox/default', ['action' => 'add', 'path' => $file['path_lower']]) ?>" class="btn btn-primary">Dodaj nowy plik</i></a>
    <?php endif; ?>
<?php endif; ?>